version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"              # přístup k Prometheovi přes http://localhost:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"              # poskytuje metriky systému
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"              # přístup k Alertmanageru přes http://localhost:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always

  nginx:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "8080:80"                # chráněný přístup přes http://localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./auth:/etc/nginx/auth
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"            # přístup přes http://localhost:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

volumes:
  grafana_data:

